{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ebook-translator.fullname" . }}-secret
  labels:
    {{- include "ebook-translator.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
  target:
    name: {{ include "ebook-translator.fullname" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: R2_ACCOUNT_ID
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.R2_ACCOUNT_ID }}
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.R2_ACCESS_KEY_ID }}
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.R2_SECRET_ACCESS_KEY }}
    - secretKey: OPENAI_API_KEYS_CSV
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.OPENAI_API_KEYS_CSV }}
    - secretKey: DEEPL_API_KEYS_CSV
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.DEEPL_API_KEYS_CSV }}
    - secretKey: GOOGLE_API_KEYS_CSV
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.GOOGLE_API_KEYS_CSV }}
    - secretKey: DEEPINFRA_API_KEYS_CSV
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.DEEPINFRA_API_KEYS_CSV }}
    - secretKey: NEXT_PUBLIC_SUPABASE_ANON_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
{{- end }}
