{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ebook-translator.fullname" . }}-ui
  labels:
    {{- include "ebook-translator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ebook-translator.fullname" . }}-ui
  template:
    metadata:
      labels:
        app: {{ include "ebook-translator.fullname" . }}-ui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ include "ebook-translator.fullname" . }}-config
            - secretRef:
                name: {{ include "ebook-translator.fullname" . }}-secret
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
{{- end }}
